const db = require('../models');
const { Product } = db;

async function seedProducts() {
return await Product.bulkCreate([
    {
        name: 'PlayStation 5',
        description: 'Consola de nueva generación con SSD ultra rápido y gráficos 4K',
        sku: 'PS5-CONSOLE-001',
        barcode: '711719541028',            
        unit_price: 599.99,
        cost_price: 450.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 5,
        max_stock: 1000,
        is_active: true,
    },
    {
        name: 'Xbox Series X',
        description: 'Consola de Microsoft con 12 teraflops de potencia gráfica',
        sku: 'XBOX-SX-001',
        barcode: '889842640649',
        unit_price: 499.99,
        cost_price: 380.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 5,
        max_stock: 800,
        is_active: true,
    },
    {
        name: 'Nintendo Switch OLED',
        description: 'Consola híbrida con pantalla OLED de 7 pulgadas',
        sku: 'NSW-OLED-001',
        barcode: '045496596804',
        unit_price: 349.99,
        cost_price: 270.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 10,
        max_stock: 500,
        is_active: true,
    },
    {
        name: 'DualSense Controller PS5',
        description: 'Control inalámbrico con retroalimentación háptica',
        sku: 'PS5-CTRL-001',
        barcode: '711719541035',
        unit_price: 69.99,
        cost_price: 45.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 20,
        max_stock: 200,
        is_active: true,
    },
    {
        name: 'Xbox Wireless Controller',
        description: 'Control inalámbrico para Xbox Series X|S',
        sku: 'XBOX-CTRL-001',
        barcode: '889842640656',
        unit_price: 59.99,
        cost_price: 40.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 25,
        max_stock: 150,
        is_active: true,
    },
    {
        name: 'Auriculares SteelSeries Arctis 7',
        description: 'Auriculares gaming inalámbricos con sonido 7.1',
        sku: 'SS-ARC7-001',
        barcode: '812816020274',
        unit_price: 149.99,
        cost_price: 100.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 15,
        max_stock: 100,
        is_active: true,
    },
    {
        name: 'The Legend of Zelda: Tears of the Kingdom',
        description: 'Aventura épica para Nintendo Switch',
        sku: 'NSW-ZELDA-001',
        barcode: '045496597313',
        unit_price: 69.99,
        cost_price: 50.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 30,
        max_stock: 300,
        is_active: true,
    },
    {
        name: 'God of War Ragnarök',
        description: 'Épica aventura nórdica para PlayStation 5',
        sku: 'PS5-GOW-001',
        barcode: '711719541042',
        unit_price: 59.99,
        cost_price: 42.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 25,
        max_stock: 250,
        is_active: true,
    },
    {
        name: 'Figura Funko Pop Master Chief',
        description: 'Figura coleccionable de Halo de 10cm',
        sku: 'FUNKO-MC-001',
        barcode: '889698147361',
        unit_price: 12.99,
        cost_price: 8.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 50,
        max_stock: 500,
        is_active: true,
    },
    {
        name: 'Playera Pokemon Pikachu',
        description: 'Camiseta oficial de algodón 100% talla M',
        sku: 'SHIRT-PIKA-M',
        barcode: '634482746875',
        unit_price: 24.99,
        cost_price: 15.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 40,
        max_stock: 200,
        is_active: true,
    },
    {
        name: 'Teclado Mecánico Razer BlackWidow',
        description: 'Teclado gaming con switches mecánicos RGB',
        sku: 'RAZER-KB-001',
        barcode: '8886419371618',
        unit_price: 129.99,
        cost_price: 85.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 12,
        max_stock: 80,
        is_active: true,
    },
    {
        name: 'Mouse Gaming Logitech G502',
        description: 'Mouse óptico con 11 botones programables',
        sku: 'LOGI-G502-001',
        barcode: '097855129208',
        unit_price: 79.99,
        cost_price: 55.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 20,
        max_stock: 120,
        is_active: true,
    },
    {
        name: 'Tarjeta de Regalo Steam $50',
        description: 'Tarjeta de regalo para la plataforma Steam',
        sku: 'STEAM-GIFT-50',
        barcode: '014633730661',
        unit_price: 50.00,
        cost_price: 45.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 100,
        max_stock: 1000,
        is_active: true,
    },
    {
        name: 'Cable HDMI 4K 2m',
        description: 'Cable HDMI premium compatible con 4K@60Hz',
        sku: 'HDMI-4K-2M',
        barcode: '612825158974',
        unit_price: 19.99,
        cost_price: 12.00,
        tax_rate: 0.16,
        unit_measure: 'm',
        min_stock: 35,
        max_stock: 300,
        is_active: true,
    },
    {
        name: 'Silla Gaming DXRacer',
        description: 'Silla ergonómica para gaming con soporte lumbar',
        sku: 'CHAIR-DX-001',
        barcode: '746892951374',
        unit_price: 299.99,
        cost_price: 200.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 5,
        max_stock: 50,
        is_active: true,
    },
    {
        name: 'Figura Link Breath of the Wild',
        description: 'Figura articulada de 15cm de The Legend of Zelda',
        sku: 'FIG-LINK-001',
        barcode: '045496593162',
        unit_price: 34.99,
        cost_price: 22.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 25,
        max_stock: 150,
        is_active: true,
    },
    {
        name: 'Mousepad Gaming XXL',
        description: 'Alfombrilla gaming extendida 900x400mm',
        sku: 'PAD-XXL-001',
        barcode: '783162745891',
        unit_price: 29.99,
        cost_price: 18.00,
        tax_rate: 0.16,
        unit_measure: 'm2',
        min_stock: 30,
        max_stock: 200,
        is_active: true,
    },
    {
        name: 'Webcam Logitech C920',
        description: 'Cámara web Full HD para streaming',
        sku: 'CAM-C920-001',
        barcode: '097855086310',
        unit_price: 89.99,
        cost_price: 60.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 15,
        max_stock: 100,
        is_active: true,
    },
    {
        name: 'Gorra Minecraft Creeper',
        description: 'Gorra ajustable oficial de Minecraft',
        sku: 'HAT-MC-001',
        barcode: '192995068773',
        unit_price: 19.99,
        cost_price: 12.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 40,
        max_stock: 250,
        is_active: true,
    },
    {
        name: 'Micrófono Blue Yeti',
        description: 'Micrófono USB profesional para streaming',
        sku: 'MIC-YETI-001',
        barcode: '988-000100',
        unit_price: 99.99,
        cost_price: 70.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 10,
        max_stock: 60,
        is_active: true,
    },
    {
        name: 'Mochila Gaming Asus ROG',
        description: 'Mochila para laptop gaming hasta 17 pulgadas',
        sku: 'BAG-ROG-001',
        barcode: '4718017456821',
        unit_price: 59.99,
        cost_price: 40.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 20,
        max_stock: 120,
        is_active: true,
    },
    {
        name: 'Monitor Gaming ASUS 24" 144Hz',
        description: 'Monitor gaming Full HD con 1ms de respuesta',
        sku: 'MON-ASUS-24',
        barcode: '4718017890456',
        unit_price: 249.99,
        cost_price: 180.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 8,
        max_stock: 50,
        is_active: true,
    },
    {
        name: 'SSD Samsung 970 EVO 1TB',
        description: 'SSD NVMe M.2 de alta velocidad',
        sku: 'SSD-SAM-1TB',
        barcode: '8806088546780',
        unit_price: 129.99,
        cost_price: 95.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 15,
        max_stock: 100,
        is_active: true,
    },
    {
        name: 'RAM Corsair Vengeance 16GB',
        description: 'Memoria DDR4 3200MHz kit 2x8GB',
        sku: 'RAM-COR-16GB',
        barcode: '843591070454',
        unit_price: 79.99,
        cost_price: 60.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 20,
        max_stock: 150,
        is_active: true,
    },
    {
        name: 'Disco Duro Seagate 2TB',
        description: 'Disco duro interno SATA 7200 RPM',
        sku: 'HDD-SEA-2TB',
        barcode: '763649029329',
        unit_price: 69.99,
        cost_price: 50.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 25,
        max_stock: 200,
        is_active: true,
    },
    {
        name: 'Fuente de Poder EVGA 650W',
        description: 'PSU 80+ Gold modular',
        sku: 'PSU-EVGA-650',
        barcode: '843368070236',
        unit_price: 99.99,
        cost_price: 75.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 12,
        max_stock: 80,
        is_active: true,
    },
    {
        name: 'Pasta Térmica Arctic MX-4',
        description: 'Compuesto térmico de alta conductividad 4g',
        sku: 'PASTE-MX4',
        barcode: '4895213300157',
        unit_price: 9.99,
        cost_price: 6.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 50,
        max_stock: 300,
        is_active: true,
    },
    {
        name: 'Cables SATA Pack 3 unidades',
        description: 'Cables SATA III de 50cm',
        sku: 'CABLE-SATA-3',
        barcode: '123456789012',
        unit_price: 12.99,
        cost_price: 8.00,
        tax_rate: 0.16,
        unit_measure: 'paquete',
        min_stock: 30,
        max_stock: 200,
        is_active: true,
    },
    {
        name: 'Cooler CPU Noctua NH-D15',
        description: 'Disipador de aire premium para CPU',
        sku: 'COOL-NOC-D15',
        barcode: '9010018100426',
        unit_price: 89.99,
        cost_price: 65.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 10,
        max_stock: 60,
        is_active: true,
    },
    {
        name: 'Tarjeta Gráfica RTX 3060',
        description: 'GPU NVIDIA GeForce RTX 3060 12GB',
        sku: 'GPU-RTX-3060',
        barcode: '894323000390',
        unit_price: 329.99,
        cost_price: 250.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 5,
        max_stock: 30,
        is_active: true,
    },
    {
        name: 'Placa Madre ASUS B550',
        description: 'Motherboard AMD AM4 con WiFi',
        sku: 'MB-ASUS-B550',
        barcode: '4718017890463',
        unit_price: 149.99,
        cost_price: 110.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 8,
        max_stock: 50,
        is_active: true,
    },
    {
        name: 'Procesador AMD Ryzen 5 5600X',
        description: 'CPU 6 núcleos 12 hilos 3.7GHz',
        sku: 'CPU-AMD-5600X',
        barcode: '730143312219',
        unit_price: 199.99,
        cost_price: 150.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 10,
        max_stock: 60,
        is_active: true,
    },
    {
        name: 'Case Fractal Design Define 7',
        description: 'Gabinete ATX con paneles de vidrio templado',
        sku: 'CASE-FD-DEF7',
        barcode: '7340172702795',
        unit_price: 159.99,
        cost_price: 120.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 5,
        max_stock: 40,
        is_active: true,
    },
    {
        name: 'Ventiladores RGB Pack 3',
        description: 'Ventiladores 120mm RGB con controlador',
        sku: 'FAN-RGB-120-3',
        barcode: '456789123456',
        unit_price: 39.99,
        cost_price: 25.00,
        tax_rate: 0.16,
        unit_measure: 'paquete',
        min_stock: 20,
        max_stock: 100,
        is_active: true,
    },
    {
        name: 'Cable Ethernet Cat6 5m',
        description: 'Cable de red Cat6 gigabit',
        sku: 'ETH-CAT6-5M',
        barcode: '789123456789',
        unit_price: 14.99,
        cost_price: 9.00,
        tax_rate: 0.16,
        unit_measure: 'm',
        min_stock: 40,
        max_stock: 250,
        is_active: true,
    },
    {
        name: 'Switch de Red 8 Puertos',
        description: 'Switch gigabit no administrable',
        sku: 'SWITCH-8P',
        barcode: '321654987123',
        unit_price: 29.99,
        cost_price: 20.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 15,
        max_stock: 80,
        is_active: true,
    },
    {
        name: 'Router WiFi 6 TP-Link',
        description: 'Router inalámbrico AX1800',
        sku: 'ROUTER-AX1800',
        barcode: '840030702289',
        unit_price: 79.99,
        cost_price: 55.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 12,
        max_stock: 70,
        is_active: true,
    },
    {
        name: 'UPS APC 650VA',
        description: 'Sistema de alimentación ininterrumpida',
        sku: 'UPS-APC-650',
        barcode: '731304333692',
        unit_price: 89.99,
        cost_price: 65.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 8,
        max_stock: 50,
        is_active: true,
    },
    {
        name: 'Hub USB 3.0 de 7 Puertos',
        description: 'Concentrador USB con adaptador de corriente',
        sku: 'HUB-USB3-7P',
        barcode: '654987321456',
        unit_price: 24.99,
        cost_price: 16.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 25,
        max_stock: 150,
        is_active: true,
    },
    {
        name: 'Adaptador WiFi USB AC600',
        description: 'Adaptador inalámbrico dual band',
        sku: 'WIFI-USB-AC600',
        barcode: '987654321987',
        unit_price: 19.99,
        cost_price: 12.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 30,
        max_stock: 200,
        is_active: true,
    },
    {
        name: 'Soporte para Monitor Dual',
        description: 'Brazo articulado para dos monitores hasta 27"',
        sku: 'MOUNT-DUAL-27',
        barcode: '147258369147',
        unit_price: 49.99,
        cost_price: 32.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 15,
        max_stock: 90,
        is_active: true,
    },
    {
        name: 'Lámpara LED para Escritorio',
        description: 'Lámpara USB con control táctil RGB',
        sku: 'LAMP-LED-USB',
        barcode: '258369147258',
        unit_price: 34.99,
        cost_price: 22.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 20,
        max_stock: 120,
        is_active: true,
    },
    {
        name: 'Organizador de Cables',
        description: 'Kit de gestión de cables para escritorio',
        sku: 'CABLE-ORG-KIT',
        barcode: '369147258369',
        unit_price: 16.99,
        cost_price: 10.00,
        tax_rate: 0.16,
        unit_measure: 'paquete',
        min_stock: 35,
        max_stock: 200,
        is_active: true,
    },
    {
        name: 'Cargador Inalámbrico Rápido',
        description: 'Base de carga inalámbrica 15W Qi',
        sku: 'CHARGE-WIFI-15W',
        barcode: '741852963741',
        unit_price: 29.99,
        cost_price: 18.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 25,
        max_stock: 150,
        is_active: true,
    },
    {
        name: 'Powerbank 20000mAh',
        description: 'Batería portátil con carga rápida PD',
        sku: 'POWER-20K-PD',
        barcode: '852963741852',
        unit_price: 39.99,
        cost_price: 26.00,
        tax_rate: 0.16,
        unit_measure: 'pza',
        min_stock: 20,
        max_stock: 120,
        is_active: true,
    },
    {
        name: 'Limpiador de Pantallas 500ml',
        description: 'Spray limpiador para monitores y dispositivos',
        sku: 'CLEAN-SCREEN-500',
        barcode: '963741852963',
        unit_price: 12.99,
        cost_price: 7.50,
        tax_rate: 0.16,
        unit_measure: 'litro',
        min_stock: 40,
        max_stock: 250,
        is_active: true,
    },
    {
        name: 'Aire Comprimido 400ml',
        description: 'Spray de aire comprimido para limpieza',
        sku: 'AIR-COMP-400',
        barcode: '159753486159',
        unit_price: 8.99,
        cost_price: 5.50,
        tax_rate: 0.16,
        unit_measure: 'litro',
        min_stock: 50,
        max_stock: 300,
        is_active: true,
    },
    {
        name: 'Alfombrilla Antiestatica',
        description: 'Mat antiestático 60x40cm para reparaciones',
        sku: 'MAT-ANTIST-60',
        barcode: '753486159753',
        unit_price: 22.99,
        cost_price: 14.00,
        tax_rate: 0.16,
        unit_measure: 'm2',
        min_stock: 15,
        max_stock: 100,
        is_active: true,
    },
    {
        name: 'Kit de Destornilladores Precisión',
        description: 'Set 32 piezas para electrónicos',
        sku: 'SCREW-KIT-32',
        barcode: '486159753486',
        unit_price: 18.99,
        cost_price: 11.00,
        tax_rate: 0.16,
        unit_measure: 'caja',
        min_stock: 25,
        max_stock: 150,
        is_active: true,
    },
    {
        name: 'Cinta Aislante Negra 20m',
        description: 'Cinta eléctrica de PVC resistente',
        sku: 'TAPE-ELEC-20M',
        barcode: '591753486197',
        unit_price: 4.99,
        cost_price: 2.50,
        tax_rate: 0.16,
        unit_measure: 'm',
        min_stock: 60,
        max_stock: 400,
        is_active: true,
    }
]);
}

module.exports = seedProducts;
