const db = require('../models');
const { Product } = db;

async function seedProducts() {
  return await Product.bulkCreate([
   {
            name: 'PlayStation 5',
            description: 'Consola de nueva generación con SSD ultra rápido y gráficos 4K',
            sku: 'PS5-CONSOLE-001',
            barcode: '711719541028',            
            unit_price: 599.99,
            cost_price: 450.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 5,
            max_stock: 1000,
            is_active: true,
        },
        {
            name: 'Xbox Series X',
            description: 'Consola de Microsoft con 12 teraflops de potencia gráfica',
            sku: 'XBOX-SX-001',
            barcode: '889842640649',
            unit_price: 499.99,
            cost_price: 380.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 5,
            max_stock: 800,
            is_active: true,
        },
        {
            name: 'Nintendo Switch OLED',
            description: 'Consola híbrida con pantalla OLED de 7 pulgadas',
            sku: 'NSW-OLED-001',
            barcode: '045496596804',
            unit_price: 349.99,
            cost_price: 270.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 10,
            max_stock: 500,
            is_active: true,
        },
        {
            name: 'DualSense Controller PS5',
            description: 'Control inalámbrico con retroalimentación háptica',
            sku: 'PS5-CTRL-001',
            barcode: '711719541035',
            unit_price: 69.99,
            cost_price: 45.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 20,
            max_stock: 200,
            is_active: true,
        },
        {
            name: 'Xbox Wireless Controller',
            description: 'Control inalámbrico para Xbox Series X|S',
            sku: 'XBOX-CTRL-001',
            barcode: '889842640656',
            unit_price: 59.99,
            cost_price: 40.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 25,
            max_stock: 150,
            is_active: true,
        },
        {
            name: 'Auriculares SteelSeries Arctis 7',
            description: 'Auriculares gaming inalámbricos con sonido 7.1',
            sku: 'SS-ARC7-001',
            barcode: '812816020274',
            unit_price: 149.99,
            cost_price: 100.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 15,
            max_stock: 100,
            is_active: true,
        },
        {
            name: 'The Legend of Zelda: Tears of the Kingdom',
            description: 'Aventura épica para Nintendo Switch',
            sku: 'NSW-ZELDA-001',
            barcode: '045496597313',
            unit_price: 69.99,
            cost_price: 50.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 30,
            max_stock: 300,
            is_active: true,
        },
        {
            name: 'God of War Ragnarök',
            description: 'Épica aventura nórdica para PlayStation 5',
            sku: 'PS5-GOW-001',
            barcode: '711719541042',
            unit_price: 59.99,
            cost_price: 42.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 25,
            max_stock: 250,
            is_active: true,
        },
        {
            name: 'Figura Funko Pop Master Chief',
            description: 'Figura coleccionable de Halo de 10cm',
            sku: 'FUNKO-MC-001',
            barcode: '889698147361',
            unit_price: 12.99,
            cost_price: 8.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 50,
            max_stock: 500,
            is_active: true,
        },
        {
            name: 'Playera Pokemon Pikachu',
            description: 'Camiseta oficial de algodón 100% talla M',
            sku: 'SHIRT-PIKA-M',
            barcode: '634482746875',
            unit_price: 24.99,
            cost_price: 15.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 40,
            max_stock: 200,
            is_active: true,
        },
        {
            name: 'Teclado Mecánico Razer BlackWidow',
            description: 'Teclado gaming con switches mecánicos RGB',
            sku: 'RAZER-KB-001',
            barcode: '8886419371618',
            unit_price: 129.99,
            cost_price: 85.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 12,
            max_stock: 80,
            is_active: true,
        },
        {
            name: 'Mouse Gaming Logitech G502',
            description: 'Mouse óptico con 11 botones programables',
            sku: 'LOGI-G502-001',
            barcode: '097855129208',
            unit_price: 79.99,
            cost_price: 55.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 20,
            max_stock: 120,
            is_active: true,
        },
        {
            name: 'Tarjeta de Regalo Steam $50',
            description: 'Tarjeta de regalo para la plataforma Steam',
            sku: 'STEAM-GIFT-50',
            barcode: '014633730661',
            unit_price: 50.00,
            cost_price: 45.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 100,
            max_stock: 1000,
            is_active: true,
        },
        {
            name: 'Cable HDMI 4K 2m',
            description: 'Cable HDMI premium compatible con 4K@60Hz',
            sku: 'HDMI-4K-2M',
            barcode: '612825158974',
            unit_price: 19.99,
            cost_price: 12.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 35,
            max_stock: 300,
            is_active: true,
        },
        {
            name: 'Silla Gaming DXRacer',
            description: 'Silla ergonómica para gaming con soporte lumbar',
            sku: 'CHAIR-DX-001',
            barcode: '746892951374',
            unit_price: 299.99,
            cost_price: 200.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 5,
            max_stock: 50,
            is_active: true,
        },
        {
            name: 'Figura Link Breath of the Wild',
            description: 'Figura articulada de 15cm de The Legend of Zelda',
            sku: 'FIG-LINK-001',
            barcode: '045496593162',
            unit_price: 34.99,
            cost_price: 22.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 25,
            max_stock: 150,
            is_active: true,
        },
        {
            name: 'Mousepad Gaming XXL',
            description: 'Alfombrilla gaming extendida 900x400mm',
            sku: 'PAD-XXL-001',
            barcode: '783162745891',
            unit_price: 29.99,
            cost_price: 18.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 30,
            max_stock: 200,
            is_active: true,
        },
        {
            name: 'Webcam Logitech C920',
            description: 'Cámara web Full HD para streaming',
            sku: 'CAM-C920-001',
            barcode: '097855086310',
            unit_price: 89.99,
            cost_price: 60.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 15,
            max_stock: 100,
            is_active: true,
        },
        {
            name: 'Gorra Minecraft Creeper',
            description: 'Gorra ajustable oficial de Minecraft',
            sku: 'HAT-MC-001',
            barcode: '192995068773',
            unit_price: 19.99,
            cost_price: 12.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 40,
            max_stock: 250,
            is_active: true,
        },
        {
            name: 'Micrófono Blue Yeti',
            description: 'Micrófono USB profesional para streaming',
            sku: 'MIC-YETI-001',
            barcode: '988-000100',
            unit_price: 99.99,
            cost_price: 70.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 10,
            max_stock: 60,
            is_active: true,
        },
        {
            name: 'Mochila Gaming Asus ROG',
            description: 'Mochila para laptop gaming hasta 17 pulgadas',
            sku: 'BAG-ROG-001',
            barcode: '4718017456821',
            unit_price: 59.99,
            cost_price: 40.00,
            tax_rate: 0.16,
            unit_measure: 'unit',
            min_stock: 20,
            max_stock: 120,
            is_active: true,
        }
  ]);
}

module.exports = seedProducts;
